### ISSUE TITLE
Bot crashes during heartbeats if social service returns an error

### ISSUE THREAD

**Issue by yeenbean** [yeenbean/pauljac3-mastodon-bot#9]
The bot is crashing during heartbeats when a social service returns an unknown error which the bot cannot process. The code needs to be refactored to handle this sort of scenario correctly.

Below is an example of errors I've encountered when this occurs.

```
    09:45: Heartbeat
error: Uncaught MastoUnexpectedError: The server returned data with an unknown encoding. The server may be down.
    at HttpNativeImpl.<anonymous> (file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:927:27)
    at Generator.next (<anonymous>)
    at file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:72:12)
    at HttpNativeImpl.createError (file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:923:16)
    at HttpNativeImpl.<anonymous> (file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:906:34)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/yeen/Library/Caches/deno/npm/registry.npmjs.org/masto/6.1.0/dist/index.js:73:58)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by yeenbean** [comment]
In `postMastoReplies()`, there are calls to functions that are not wrapped in a try/catch statement. This oversight may be what's causing the bot to produce this error.

https://github.com/yeenbean/pauljac3-mastodon-bot/blob/a73c961d8084119abaf34588eca7fc1490874797/src/app.ts#L322
